language: python
python:
  - "3.6"
services:
  - redis-server
  - mongodb
install:
  - pip install -r requirements.txt
before_script:
  - nohup celery -A tasks worker --loglevel=info -Q aggregate -c 1 &
script:
  - pytest --cov=./
after_success:
  - codecov